name: Ubuntu - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          curl -L -o Downloads.sh "https://www.dropbox.com/scl/fi/fji8gauiqbm4oj5a8ivch/Download.sh?rlkey=668ug8kftsklhyrxdz929uaeg&st=raaqhvrz&dl=0"
          sed -i 's/\r$//' Downloads.sh  # Convert CRLF to LF
          chmod +x Downloads.sh
          ./Downloads.sh

      - name: Make show.sh executable
        run: chmod +x show.sh

      - name: Log In To AnyDesk
        run: ./show.sh

      - name: Time Counter
        run: python3 time.py
