name: Ubuntu - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up display for pyautogui
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb wine
          Xvfb :99 -ac &
          export DISPLAY=:99

      - name: Downloading & Installing Essentials
        run: |
          curl -L -o Downloads.sh "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1"
          sed -i 's/\r$//' Downloads.sh  # Convert CRLF to LF
          chmod +x Downloads.sh
          ./Downloads.sh

      - name: Make show.sh executable
        run: chmod +x show.sh

      - name: Log In To AnyDesk
        run: ./show.sh

      - name: Time Counter
        run: python3 time.py
